[package]
name = "minrusty-volume"
version = "0.1.0"
authors = ["Simon <simonwoodburyforget@gmail.com>"]
edition = "2018"
license = "GNUv3"
repository = "https://github.com/SimonWoodburyForget/minrusty/"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vek = "0.9"
